services:
  mongodb:
    build: ./mongodb
    image: arjunkeellapati/mongodb:v1
    container_name: mongodb
    volumes:
    - mongodb:/data/db
  catalogue:
    build:
      context: ./catalogue
      dockerfile: dockerfile
    image: arjunkeellapati/catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb
  redis:
    image: redis:7.0
    container_name: redis
    volumes:
    - mongodb:/data
  mysql:
    build: ./mysql
    image: arjunkeellapati/mysql:v1
    container_name: mysql
    volumes:
    - mongodb:/var/lib/mysql
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    volumes:
    - mongodb:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
  user:
    build: ./user
    image: arjunkeellapati/user:v1
    container_name: user
    depends_on:
    - mongodb
    - redis
  cart:
    build: ./cart
    image: arjunkeellapati/cart:v1
    container_name: cart
    depends_on:
    - redis
    - catalogue
  shipping:
    build: ./shipping
    image: arjunkeellapati/shipping:v1
    container_name: shipping
    depends_on:
    - mysql
    - cart
  payment:
    build: ./payment
    image: arjunkeellapati/payment:v1
    container_name: payment
    depends_on:
    - rabbitmq
    - cart
    - user
  frontend:
    build: ./frontend
    image: arjunkeellapati/frontend:v1
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - cart
    - user
    - payment
    - shipping


networks:
  default:
    driver: bridge
    name: roboshop
    external: false # true if you have created metwork manually using docker network command 

volumes:
  redis:
  mongodb:
  rabbitmq:
  mysql:
